  - name: Add MongoDB key
    apt_key: keyserver=keyserver.ubuntu.com id=7F0CEB10
    sudo: yes
    tags:
    - mongodb
    - run

  - name: Add MongoDB repository
    apt_repository: repo='deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' state=present
    sudo: yes
    tags:
    - mongodb
    - run

  - name: Install MongoDB
    apt: pkg=mongodb-org update_cache=yes
    sudo: yes
    tags:
    - mongodb
    - run

  - name: Increase allowed namespace size for mongodb
    lineinfile: dest=/etc/mongod.conf regexp="{{ item.regexp }}" line="{{ item.line }}"
    sudo: yes
    with_items:
    - {regexp: '\# nssize \= \<size\>', line: 'nssize = 255' }
    - {regexp: 'bind_ip = 127.0.0.1', line: 'bind_ip = 0.0.0.0' }
    tags:
    - mongodb
    - run
  
  - name: Start MongoDB
    service: name=mongod state=restarted
    sudo: yes
    tags:
    - mongodb
    - run

